### ISSUE TITLE
Design ShapleQ cli & config

### ISSUE THREAD

**Issue by elon0823** [paust-team/pirius#26]
## Broker
`shapleQ`

### Configs
```yaml
port: 1101  # broker port
log-dir: ~/.shapleq/log # log directory
data-dir: ~/.shapleq/data # data directory
log-level: DEBUG # DEBUG/INFO/WARNING/ERROR
zookeeper:
  port: 2181 
  host: localhost
  timeout: 3 # zookeeper connection timeout(seconds)
```
#### start
- options
  - `-d` daemon mode
  - `-i` config path (default: ~/.shapleq/config/broker/config.yml)

#### stop
- options
  - `—clean` clean data dir

#### status
- output
```
Active / Inactive
Running on port 1101
```

## Client
`shapleQ-cli`

### Configs
```yaml
broker: 
- port: 1101 # broker port
- host: localhost # broker address
timeout: 3 # connection timeout (seconds)
log-level: DEBUG # DEBUG/INFO/WARNING/ERROR


```

### Commands

* Common options

#### publish
- args
  1. `byte-string-data-to-publish`
- options
  - `-i` config path (default: ~/.shapleq/config/producer/config.yml)
  - `-f` file path
  - `-n` topic name

#### subscribe
- options
   - `-i` config path (default: ~/.shapleq/config/consumer/config.yml)
  - `-n` topic name
  - `-o` start offset

#### topic
 - `-i` config path (default: ~/.shapleq/config/admin/config.yml)
##### create
- options
  - `-n` topic name
  - `-m` topic meta(string)

##### delete
- options
  - `-n` topic name

##### describe
- options
  - `-n` topic name
